const weaponEffects = {
    //CORE, LONG RIM, WALLFLOWER, KTB
    "npcf_devils_cough_shotgun_assassin": "Shotgun",
    "mw_exo_steelpunch_heavy_needlebeam": "Needle Beam",
    "mw_exo_sting_heavy_anti_armor_rifle": "AMR",
    "npcf_acid_spittle_monstrosity": "Nanobot Whip",
    "mw_andromeda_pattern_heavy_laser_rifle": "Lasers",
    "mw_annihilation_nexus": "Nexus",
    "mw_annihilator": "Annihilator",
    "npcf_anti_armor_weapon_human": "AMR",
    "npcf_anti_armor_weapon_squad": "AMR",
    "mw_anti_materiel_rifle": "AMR",
    "npcf_anti_materiel_rifle_sniper": "AMR",
    "mw_barbarossa_integrated": "Apocalypse Rail",
    "mw_arc_projector": "PPC",
    "mw_assault_cannon": "HMG",
    "mw_assault_rifle": "Assault Rifle",
    "mw_autogun": "Assault Rifle",
    "mw_autopod": "AutoPod",
    "mw_blackspot_targeting_laser": "LockOn",
    "npcf_boarding_leash_pirate": "DefaultMelee",
    "mw_bolt_nexus": "Nexus",
    "mw_bolt_thrower": "Bolt Thrower",
    "npcf_bombard_cannon_bombard": "Apocalypse Rail",
    "mw_bristlecrown_flechette_launcher": "Flechette Launcher",
    "mw_exo_brood_siblings_molt": "Brood Siblings Molt",
    "mw_burst_launcher": "Burst Launcher",
    "npcf_carbon_fiber_sword_ronin": "DefaultMelee",
    "mw_catalyst_pistol": "Plasma Rifle",
    "mw_catalytic_hammer": "DefaultMelee",
    "mw_chain_axe": "DefaultMelee",
    "npcf_chain_axe_berserker": "DefaultMelee",
    "mw_charged_blade": "Charged Blade",
    "npcf_claws_monstrosity": "Plasma Talons",
    "mw_combat_drill": "Combat Drill",
    "npcf_combat_knife_assault": "DefaultMelee",
    "npcf_combat_shotgun_sentinel": "Shotgun",
    "npcf_concussion_gun_spacer": "Burst Launcher",
    "mw_concussion_missiles": "Missile",
    "mw_cutter_mkii_plasma_torch": "Plasma Torch",
    "mw_cyclone_pulse_rifle": "Cyclone Pulse Rifle",
    "mw_d_d_288": "DD 288",
    "mw_daisy_cutter": "Shotgun",
    "mw_deck_sweeper_automatic_shotgun": "Shotgun",
    "npcf_demolition_hammer_demolisher": "Hammer",
    "mw_displacer": "Displacer",
    "npcf_drum_shotgun_goliath": "Shotgun",
    "npcf_dual_shotguns_breacher": "Shotgun",
    "nrfaw-npc_npcf_skirmisher_kit_explosive_rifle_strider": "Bolt Thrower",
    "mw_ferrofluid_lance": "War Pike",
    "npcf_flak_cannon_engineer": "Mortar",
    "npcf_flamethrower_pyro": "Flamethrower",
    "npcf_flechette_shot_breacher": "Shotgun",
    "mw_fold_knife": "DefaultMelee",
    "mw_fuel_rod_gun": "Fuel Rod Gun",
    "mw_fusion_rifle": "Plasma Rifle",
    "mw_gandiva_missiles": "Missile",
    "mw_ghast_nexus": "Nexus",
    "mw_ghoul_nexus": "Nexus",
    "npcf_grav_grenade_launcher_seeder": "Displacer",
    "npcf_graviton_lance_barricade": "Warp Rifle",
    "mw_gravity_gun": "Displacer",
    "npcf_gravity_rifle_spacer": "Warp Rifle",
    "mw_hammer_u_rpl": "HMG",
    "mw_hand_cannon": "Pistol",
    "npcf_harpoon_cannon_berserker": "ArcBow",
    "npcf_heated_blade_assassin": "DefaultMelee",
    "npcf_heavy_assault_rifle_assault": "Assault Rifle",
    "npcf_heavy_assault_shield_bastion": "DefaultMelee",
    "mw_heavy_charged_blade": "Charged Blade",
    "mw_heavy_machine_gun": "HMG",
    "mw_heavy_melee_weapon": "DefaultMelee",
    "npcf_hellfire_projector_ultra": "Annihilator",
    "npcf_hex_missiles_hornet": "Missile",
    "mw_caliban_integrated": "Shotgun",
    "mw_hhs_155_cannibal": "Shotgun",
    "mw_howitzer": "Mortar",
    "npcf_hunter_killer_nexus_hive": "Nexus",
    "mw_impact_lance": "Impact Lance",
    "mw_impaler_nailgun": "Bolt Thrower",
    "nrfaw-npc_npcf_judgement_shotgun_avenger": "Shotgun",
    "mw_kinetic_hammer": "Hammer",
    "mw_krakatoa_thermobaric_flamethrower": "Flamethrower",
    "mw_kraul_rifle": "Kraul Rifle",
    "mw_lancaster_integrated": "Latch Drone",
    "mw_leviathan_heavy_assault_cannon": "Leviathan",
    "npcf_light_laser_aegis": "Lasers",
    "npcf_light_machine_gun_archer": "HMG",
    "mw_raleigh_integrated": "Burst Launcher",
    "npcf_machine_pistol_specter": "Pistol",
    "nrfaw-npc_npcf_sapper_kit_mag_shotgun_strider": "Shotgun",
    "mw_magnetic_cannon": "Impact Lance",
    "mw_emperor_integrated": "ArcBow",
    "npcf_marker_rifle_scout": "LockOn",
    "npcf_melee_weapon_human": "DefaultMelee",
    "mw_mimic_gun": "PPC",
    "npcf_missile_launcher_ace": "Missile",
    "npcf_missile_pods_rainmaker": "Missiles",
    "mw_missile_rack": "Missile",
    "npcf_missile_swarm_ace": "Missiles",
    "npcf_monowire_sword_specter": "DefaultMelee",
    "mw_mortar": "Mortar",
    "npcf_nail_gun_berserker": "Kraul Rifle",
    "mw_nanobot_whip": "Nanobot Whip",
    "mw_nanocarbon_sword": "DefaultMelee",
    "npcf_napalm_bomb_pyro": "Mortar",
    "mw_nexus_hunter_killer": "Nexus",
    "mw_nexus_light": "Nexus",
    "npcf_nova_missiles_operator": "Missile",
    "mw_oracle_lmg_i": "Assault Rifle",
    "mw_pinaka_missiles": "MissilePinaka",
    "mw_pistol": "Pistol",
    "mw_exo_plasma_maul": "Plasma Maul",
    "mw_tokugawa_alt_enkidu_integrated": "Plasma Talons",
    "mw_plasma_thrower": "Plasma Thrower",
    "mw_power_knuckles": "DefaultMelee",
    "npcf_primary_weapon_squad": "Assault Rifle",
    "mw_prototype_1": "PPC",
    "mw_prototype_2": "PPC",
    "mw_prototype_3": "PPC",
    "npcf_pulse_laser_scourer": "Veil Rifle",
    "mw_rail_rifle": "Railgun",
    "mw_railgun": "Railgun",
    "npcf_ram_cannon_cataphract": "DefaultMelee",
    "npcf_ranged_weapon_human": "Pistol",
    "nrfaw-npc_npcf_marksman_kit_ranger_long_rifle_strider": "AMR",
    "npcf_raptor_plasma_rifle_operator": "Plasma Rifle",
    "npcf_ravager_turret_ultra": "HMG",
    "npcf_repeater_cannon_bombard": "Mortar",
    "mw_retort_loop": "Retort Loop",
    "npcf_retractable_sword_sentinel": "DefaultMelee",
    "nrfaw-npc_npcf_ripper_claws_lurker": "Nanobot Whip",
    "mw_rocket_propelled_grenade": "Missile",
    "npcf_rotary_grenade_launcher_bastion": "Mortar",
    "nrfaw-npc_npcf_scouring_whip_lurker": "Nanobot Whip",
    "npcf_seeker_cloud_hive": "Nexus",
    "mw_segment_knife": "DefaultMelee",
    "mw_sharanga_missiles": "Missiles",
    "mw_shatterhead_colony_missiles": "Missile",
    "mw_shock_knife": "DefaultMelee",
    "mw_shotgun": "Shotgun",
    "nrfaw-npc_npcf_siege_kit_shoulder_mortar_strider": "Mortar",
    "mw_siege_cannon": "Mortar",
    "mw_slag_cannon": "Slag Cannon",
    "nrfaw-npc_npcf_slug_pistol_avenger": "Pistol",
    "mw_smartgun": "Assault Rifle",
    "mw_sol_pattern_laser_rifle": "Lasers",
    "npcf_stinger_pistol_hornet": "Pistol",
    "mw_stub_cannon": "HMG",
    "mw_swarm_hive_nanites": "Nexus",
    "mw_tachyon_lance": "Tachyon Lance",
    "mw_tactical_knife": "DefaultMelee",
    "mw_tactical_melee_weapon": "DefaultMelee",
    "mw_terashima_blade": "DefaultMelee",
    "mw_thermal_lance": "Thermal Rifle",
    "npcf_thermal_lance_scourer": "Thermal Rifle",
    "mw_thermal_pistol": "Thermal Rifle",
    "mw_thermal_rifle": "Thermal Rifle",
    "mw_xiaoli_combat_sheathe": "DefaultMelee",
    "mw_torch": "Torch",
    "npcf_underslung_grenade_launcher_assault": "Mortar",
    "mw_unraveler": "Retort Loop",
    "mw_variable_sword": "DefaultMelee",
    "mw_veil_rifle": "Veil Rifle",
    "mw_vijaya_rockets": "Missile",
    "mw_vorpal_gun": "Retort Loop",
    "mw_vulture_dmr": "BattleRifle",
    "mw_war_pike": "War Pike",
    "mw_warp_rifle": "Warp Rifle",
    "mw_sherman_integrated": "Railgun",
    "default_tech_attack": "DefaultTech",
    "lwfx_stabilize": "Stabilize",
    //SOLSTICE RAIN
    "mw_xc_br_battle_rifle": "BattleRifle",
    "mw_xc_dpm_predator_nexus": "Nexus",
    //DUSTGRAVE
    "mw_tempest_charged_blade": "TempestBlade",
    "mw_hurricane_cluster_projector": "CannonAirburst",
    "mw_reaper_assault_cannon": "Leviathan",
    "mw_shock_baton": "ShockBaton",
    "mw_blast_pick": "BlastPick",
    "mw_brutus_wrecker": "DefaultMelee",
    "mw_brutus_shield": "DefaultMelee",
    //DUSTGRAVE NPCs
    "npcf_rock_drill_industrial_mech": "Combat Drill",
    "npcf_fusion_cutter_industrial_mech": "Plasma Torch",
    "npcf_rivet_cannon_industrial_mech": "Bolt Thrower",
    "npcf_buzzsaw_industrial_mech": "DefaultMelee",
    "npcf_wrecker_industrial_mech": "DefaultMelee",
    "npcf_industrial_clamps_industrial_mech": "DefaultMelee",
    "npcf_gyrojet_cannon_spec_op": "Missile",
    "npcf_serrated_machete_spec_op": "DefaultMelee",
    "npcf_assimilaiton_maw_horror": "AssimilationMaw",
    "npcf_disruptor_whip_horror": "DisruptorWhip",
    //SIRENS SONG
    "npc_Leech_PairedTalonsMKII": "Plasma Talons",
    "npc_Tempest_NaniteMonsoonDispensers": "Nexus",
    "npc_Tempest_TyphoonNaniteCannon": "Nexus",
    "npc_PDCTurret": "Leviathan",

    /*
    Custom effects go under here. You can associate the name of a feature in Foundry to the name of a macro in the compendium, like so:

        "Data Dart": "Nexus"
        "Anticausal Thought": "Displacer"
        "Example Custom Weapon": "Assault Rifle",

    If your feature has quotes in the name, use backslashes (\) to prevent issues:

        "\"Hornet\" Light Submachine Gun": "Assault Rifle",

    If there aren't any effects you like, you can unlock the compendium and add your own.
    If Foundry is open, refreshing the window will reflect changes made here; you don't need to reload the world.

    !! BACK UP YOUR CHANGES BEFORE A MODULE UPDATE OR THEY'LL BE LOST !!
    */
    "Example Custom Weapon": "Assault Rifle",
    "\"SPAGHETTI\" Weaponized JavaScript Module": "DefaultTech",
    };

export { weaponEffects };
