export const EFFECTS_WEAR_AND_TEAR = {
    "lwfx_overcharge": "Overcharge",
    "lwfx_overheat_critical_reactor_failure": "Critical Reactor Failure",
    "lwfx_overheat_destabilized_power_plant": "Destabilized Power Plant",
    "lwfx_overheat_emergency_shunt": "Emergency Shunt",
    "lwfx_overheat_irreversible_meltdown": "Irreversible Meltdown",
    "lwfx_overheat_meltdown_3": "Meltdown",
    "lwfx_overheat_meltdown_2": "Meltdown",
    "lwfx_overheat_meltdown_1": "Meltdown",
    "lwfx_overheat_power_failure": "Power Failure",
    "lwfx_stabilize": "Stabilize",
    "lwfx_structure_glancing_blow": "Glancing Blow",
    "lwfx_structure_system_trauma": "Pre System Trauma",
    "lwfx_structure_secondary": "System Trauma",
    "lwfx_structure_direct_hit_3": "Direct Hit 2",
    "lwfx_structure_direct_hit_2": "Direct Hit 2",
    "lwfx_structure_direct_hit_1": "Direct Hit 1",
    "lwfx_structure_crushing_hit": "Crushing Hit",
    "lwfx_monstrosity_fatal": "Monstrosity Fatal Hit",
    "lwfx_monstrosity_direct_hit_3": "Monstrosity Direct Hit 2",
    "lwfx_monstrosity_direct_hit_2": "Monstrosity Direct Hit 2",
    "lwfx_monstrosity_direct_hit_1": "Monstrosity Direct Hit 1",
    "lwfx_monstrosity_dismember": "Monstrosity Dismemberment",
    "lwfx_monstrosity_powerful_hit": "Monstrosity Powerful Hit",
    "lwfx_monstrosity_glancing_hit": "Monstrosity Glancing Hit",
};

export const EFFECTS_GEAR = {
    //NON-ITEM EFFECTS
    "default_tech_attack": "DefaultTech",
    "lwfx_default_melee": "DefaultMelee",
    "lwfx_default_ranged": "Pistol",

    //CORE, LONG RIM, WALLFLOWER, KTB
    "mw_andromeda_pattern_heavy_laser_rifle": "Lasers",
    "mw_annihilation_nexus": "Nexus",
    "mw_annihilator": "Annihilator",
    "mw_anti_materiel_rifle": "AMR",
    "mw_arc_projector": "PPC",
    "mw_assault_cannon": "HMG",
    "mw_assault_rifle": "Assault Rifle",
    "mw_autogun": "Assault Rifle",
    "mw_autopod": "AutoPod",
    "mw_barbarossa_integrated": "Apocalypse Rail",
    "mw_blackspot_targeting_laser": "LockOn",
    "mw_bolt_nexus": "Nexus",
    "mw_bolt_thrower": "Bolt Thrower",
    "mw_bristlecrown_flechette_launcher": "Flechette Launcher",
    "mw_burst_launcher": "Burst Launcher",
    "mw_caliban_integrated": "Shotgun",
    "mw_catalyst_pistol": "Plasma Rifle",
    "mw_catalytic_hammer": "DefaultMelee",
    "mw_chain_axe": "DefaultMelee",
    "mw_charged_blade": "Charged Blade",
    "mw_combat_drill": "Combat Drill",
    "mw_concussion_missiles": "Missile",
    "mw_cutter_mkii_plasma_torch": "Plasma Torch",
    "mw_cyclone_pulse_rifle": "Cyclone Pulse Rifle",
    "mw_d_d_288": "DD 288",
    "mw_daisy_cutter": "Shotgun",
    "mw_deck_sweeper_automatic_shotgun": "Shotgun",
    "mw_displacer": "Displacer",
    "mw_emperor_integrated": "ArcBow",
    "mw_exo_brood_siblings_molt": "Brood Siblings Molt",
    "mw_exo_plasma_maul": "Plasma Maul",
    "mw_exo_steelpunch_heavy_needlebeam": "Needle Beam",
    "mw_exo_sting_heavy_anti_armor_rifle": "AMR",
    "mw_ferrofluid_lance": "War Pike",
    "mw_fold_knife": "DefaultMelee",
    "mw_fuel_rod_gun": "Fuel Rod Gun",
    "mw_fusion_rifle": "Plasma Rifle",
    "mw_gandiva_missiles": "Missile",
    "mw_ghast_nexus": "Nexus",
    "mw_ghoul_nexus": "Nexus",
    "mw_gravity_gun": "Displacer",
    "mw_hammer_u_rpl": "HMG",
    "mw_hand_cannon": "Pistol",
    "mw_heavy_charged_blade": "Charged Blade",
    "mw_heavy_machine_gun": "HMG",
    "mw_heavy_melee_weapon": "DefaultMelee",
    "mw_hhs_155_cannibal": "Shotgun",
    "mw_howitzer": "Mortar",
    "mw_impact_lance": "Impact Lance",
    "mw_impaler_nailgun": "Bolt Thrower",
    "mw_kinetic_hammer": "Hammer",
    "mw_krakatoa_thermobaric_flamethrower": "Flamethrower",
    "mw_kraul_rifle": "Kraul Rifle",
    "mw_lancaster_integrated": "Latch Drone",
    "mw_leviathan_heavy_assault_cannon": "Leviathan",
    "mw_magnetic_cannon": "Impact Lance",
    "mw_mimic_gun": "PPC",
    "mw_missile_rack": "Missile",
    "mw_mortar": "Mortar",
    "mw_nanobot_whip": "Nanobot Whip",
    "mw_nanocarbon_sword": "DefaultMelee",
    "mw_nexus_hunter_killer": "Nexus",
    "mw_nexus_light": "Nexus",
    "mw_oracle_lmg_i": "Assault Rifle",
    "mw_pinaka_missiles": "MissilePinaka",
    "mw_pistol": "Pistol",
    "mw_plasma_thrower": "Plasma Thrower",
    "mw_power_knuckles": "DefaultMelee",
    "mw_prototype_1": "PPC",
    "mw_prototype_2": "PPC",
    "mw_prototype_3": "PPC",
    "mw_rail_rifle": "Railgun",
    "mw_railgun": "Railgun",
    "mw_raleigh_integrated": "Burst Launcher",
    "mw_retort_loop": "Retort Loop",
    "mw_rocket_propelled_grenade": "Missile",
    "mw_segment_knife": "DefaultMelee",
    "mw_sharanga_missiles": "Missiles",
    "mw_shatterhead_colony_missiles": "Missile",
    "mw_sherman_integrated": "Railgun",
    "mw_shock_knife": "DefaultMelee",
    "mw_shotgun": "Shotgun",
    "mw_siege_cannon": "Mortar",
    "mw_slag_cannon": "Slag Cannon",
    "mw_smartgun": "Assault Rifle",
    "mw_sol_pattern_laser_rifle": "Lasers",
    "mw_stub_cannon": "HMG",
    "mw_swarm_hive_nanites": "Nexus",
    "mw_tachyon_lance": "Tachyon Lance",
    "mw_tactical_knife": "DefaultMelee",
    "mw_tactical_melee_weapon": "DefaultMelee",
    "mw_terashima_blade": "DefaultMelee",
    "mw_thermal_lance": "Thermal Rifle",
    "mw_thermal_pistol": "Thermal Rifle",
    "mw_thermal_rifle": "Thermal Rifle",
    "mw_tokugawa_alt_enkidu_integrated": "Plasma Talons",
    "mw_torch": "Torch",
    "mw_unraveler": "Retort Loop",
    "mw_variable_sword": "DefaultMelee",
    "mw_veil_rifle": "Veil Rifle",
    "mw_vijaya_rockets": "Missile",
    "mw_vorpal_gun": "Retort Loop",
    "mw_vulture_dmr": "BattleRifle",
    "mw_war_pike": "War Pike",
    "mw_warp_rifle": "Warp Rifle",
    "mw_xiaoli_combat_sheathe": "DefaultMelee",
    "npcf_acid_spittle_monstrosity": "Nanobot Whip",
    "npcf_anti_armor_weapon_human": "AMR",
    "npcf_anti_armor_weapon_squad": "AMR",
    "npcf_anti_materiel_rifle_sniper": "AMR",
    "npcf_boarding_leash_pirate": "DefaultMelee",
    "npcf_bombard_cannon_bombard": "Apocalypse Rail",
    "npcf_carbon_fiber_sword_ronin": "DefaultMelee",
    "npcf_chain_axe_berserker": "DefaultMelee",
    "npcf_claws_monstrosity": "Plasma Talons",
    "npcf_combat_knife_assault": "DefaultMelee",
    "npcf_combat_shotgun_sentinel": "Shotgun",
    "npcf_concussion_gun_spacer": "Burst Launcher",
    "npcf_demolition_hammer_demolisher": "Hammer",
    "npcf_devils_cough_shotgun_assassin": "Shotgun",
    "npcf_drum_shotgun_goliath": "Shotgun",
    "npcf_dual_shotguns_breacher": "Shotgun",
    "npcf_flak_cannon_engineer": "Mortar",
    "npcf_flamethrower_pyro": "Flamethrower",
    "npcf_flechette_shot_breacher": "Shotgun",
    "npcf_grav_grenade_launcher_seeder": "Displacer",
    "npcf_graviton_lance_barricade": "Warp Rifle",
    "npcf_gravity_rifle_spacer": "Warp Rifle",
    "npcf_harpoon_cannon_berserker": "ArcBow",
    "npcf_heated_blade_assassin": "DefaultMelee",
    "npcf_heavy_assault_rifle_assault": "Assault Rifle",
    "npcf_heavy_assault_shield_bastion": "DefaultMelee",
    "npcf_hellfire_projector_ultra": "Annihilator",
    "npcf_hex_missiles_hornet": "Missile",
    "npcf_hunter_killer_nexus_hive": "Nexus",
    "npcf_light_laser_aegis": "Lasers",
    "npcf_light_machine_gun_archer": "HMG",
    "npcf_machine_pistol_specter": "Pistol",
    "npcf_marker_rifle_scout": "LockOn",
    "npcf_melee_weapon_human": "DefaultMelee",
    "npcf_missile_launcher_ace": "Missile",
    "npcf_missile_pods_rainmaker": "Missiles",
    "npcf_missile_swarm_ace": "Missiles",
    "npcf_monowire_sword_specter": "DefaultMelee",
    "npcf_nail_gun_berserker": "Kraul Rifle",
    "npcf_napalm_bomb_pyro": "Mortar",
    "npcf_nova_missiles_operator": "Missile",
    "npcf_primary_weapon_squad": "Assault Rifle",
    "npcf_pulse_laser_scourer": "Veil Rifle",
    "npcf_ram_cannon_cataphract": "DefaultMelee",
    "npcf_ranged_weapon_human": "Pistol",
    "npcf_raptor_plasma_rifle_operator": "Plasma Rifle",
    "npcf_ravager_turret_ultra": "HMG",
    "npcf_repeater_cannon_bombard": "Mortar",
    "npcf_retractable_sword_sentinel": "DefaultMelee",
    "npcf_rotary_grenade_launcher_bastion": "Mortar",
    "npcf_seeker_cloud_hive": "Nexus",
    "npcf_stinger_pistol_hornet": "Pistol",
    "npcf_thermal_lance_scourer": "Thermal Rifle",
    "npcf_underslung_grenade_launcher_assault": "Mortar",
    "nrfaw-npc_npcf_judgement_shotgun_avenger": "Shotgun",
    "nrfaw-npc_npcf_marksman_kit_ranger_long_rifle_strider": "AMR",
    "nrfaw-npc_npcf_ripper_claws_lurker": "Nanobot Whip",
    "nrfaw-npc_npcf_sapper_kit_mag_shotgun_strider": "Shotgun",
    "nrfaw-npc_npcf_scouring_whip_lurker": "Nanobot Whip",
    "nrfaw-npc_npcf_siege_kit_shoulder_mortar_strider": "Mortar",
    "nrfaw-npc_npcf_skirmisher_kit_explosive_rifle_strider": "Bolt Thrower",
    "nrfaw-npc_npcf_slug_pistol_avenger": "Pistol",


    //SOLSTICE RAIN
    "mw_xc_br_battle_rifle": "BattleRifle",
    "mw_xc_dpm_predator_nexus": "Nexus",

    //WINTER SCAR
    "mw_shrapnel_cannon": "Shrapnel Cannon",
    "mw_fusion_torch": "Plasma Torch",
    "mw_superthermal_blade": "Charged Blade",
    "mw_integrated_shock_claws": "Shock Claws",
    "npc_mbt_smoothbore_cannon": "Apocalypse Rail",
    "npc_mbt_railgun": "Railgun",
    "npc_mbt_antares-pattern_laser_cannon": "Lasers",
    "npc_mbt_anti-tank_gun": "Apocalypse Rail",
    "npc_mbt_streetsweeper_canister_projector": "CannonAirburst",
    "npc_mbt_pintle-mounted_machine_gun": "HMG",
    "npc_mbt_anti-armor_missiles": "Missile",
    "npc_mbt_marker_nexus": "Nexus",
    "npc_mbt_skylight_anti-air_laser": "Lasers",
    "npc_mbt_multi-directional_charges": "Flechette Launcher",

    //DUSTGRAVE
    "mw_blast_pick": "BlastPick",
    "mw_brutus_shield": "DefaultMelee",
    "mw_brutus_wrecker": "DefaultMelee",
    "mw_hurricane_cluster_projector": "CannonAirburst",
    "mw_reaper_assault_cannon": "Leviathan",
    "mw_shock_baton": "ShockBaton",
    "mw_tempest_charged_blade": "TempestBlade",

    //DUSTGRAVE NPCs
    "npcf_assimilaiton_maw_horror": "AssimilationMaw",
    "npcf_buzzsaw_industrial_mech": "DefaultMelee",
    "npcf_disruptor_whip_horror": "DisruptorWhip",
    "npcf_fusion_cutter_industrial_mech": "Plasma Torch",
    "npcf_gyrojet_cannon_spec_op": "Missile",
    "npcf_industrial_clamps_industrial_mech": "DefaultMelee",
    "npcf_rivet_cannon_industrial_mech": "Bolt Thrower",
    "npcf_rock_drill_industrial_mech": "Combat Drill",
    "npcf_serrated_machete_spec_op": "DefaultMelee",
    "npcf_wrecker_industrial_mech": "DefaultMelee",

    //SIRENS SONG
    "npc_Leech_PairedTalonsMKII": "Plasma Talons",
    "npc_PDCTurret": "Leviathan",
    "npc_Tempest_NaniteMonsoonDispensers": "Nexus",
    "npc_Tempest_TyphoonNaniteCannon": "Nexus",

    //NPC REBAKE
    "npc-rebake_npcf_missile_launcher_ace": "Missile",
    "npc-rebake_npcf_missile_swarm_ace": "Missiles",
    "npc-rebake_npcf_light_laser_aegis": "Lasers",
    "npc-rebake_npcf_light_machine_gun_archer": "HMG",
    "npc-rebake_npcf_heated_blade_assassin": "DefaultMelee",
    "npc-rebake_npcf_devils_cough_shotgun_assassin": "Shotgun",
    "npc-rebake_npcf_weapon_heavy_assault": "Assault Rifle",
    "npc-rebake_npcf_weapon_combat_knife": "DefaultMelee",
    "npc-rebake_npcf_weapon_underslung_grenade": "Mortar",
    "npc-rebake_npcf_graviton_lance_barricade": "Warp Rifle",
    "npc-rebake_npcf_rotary_grenade_launcher_bastion": "Mortar",
    "npc-rebake_npcf_heavy_assault_shield_bastion": "DefaultMelee",
    "npc-rebake_npcf_chain_axe_berserker": "DefaultMelee",
    "npc-rebake_npcf_harpoon_cannon_berserker": "ArcBow",
    "npc-rebake_npcf_bombard_cannon_bombard": "Apocalypse Rail",
    "npc-rebake_npcf_dual_shotguns_breacher": "Shotgun",
    "npc-rebake_npcf_ram_cannon_cataphract": "DefaultMelee",
    "npc-rebake_npcf_demolition_hammer_demolisher": "Hammer",
    "npc-rebake_npcf_earthshatter_demolisher": "Hammer",
    "npc-rebake_npcf_flak_cannon_engineer": "Mortar",
    "npc-rebake_npcf_drum_shotgun_goliath": "Shotgun",
    "npc-rebake_npcf_hunter_killer_nexus_hive": "Nexus",
    "npc-rebake_npcf_stinger_pistol_hornet": "Pistol",
    "npc-rebake_npcf_raptor_plasma_rifle_operator": "Plasma Rifle",
    "npc-rebake_npcf_flamethrower_pyro": "Flamethrower",
    "npc-rebake_npcf_missile_pods_rainmaker": "Missiles",
    "npc-rebake_npcf_carbon_fiber_sword_ronin": "DefaultMelee",
    "npc-rebake_npcf_thermal_lance_scourer": "Thermal Rifle",
    "npc-rebake_npcf_marker_rifle_scout": "LockOn",
    "npc-rebake_npcf_grav_grenade_launcher_seeder": "Displacer",
    "npc-rebake_npcf_combat_shotgun_sentinel": "Shotgun",
    "npc-rebake_npcf_retractable_sword_sentinel": "DefaultMelee",
    "npc-rebake_npcf_anti_materiel_rifle_sniper": "AMR",
    "npc-rebake_npcf_monowire_sword_specter": "DefaultMelee",
    "npc-rebake_npcf_machine_pistol_specter": "Pistol",
    "npc-rebake_npcf_dmr_artillery_grunt": "AMR",
    "npc-rebake_npcf_shoulder_mortar_artillery_grunt": "Mortar",
    "npc-rebake_npcf_survival_pistol_artillery_grunt": "Pistol",
    "npc-rebake_npcf_shotgun_defender_grunt": "Shotgun",
    "npc-rebake_npcf_assault_rifle_striker_grunt": "Assault Rifle",
    "npc-rebake_npcf_heavy_blade_striker_grunt": "DefaultMelee",
    "npc-rebake_npcf_hellfire_projector_ultra": "Annihilator",
    "npc-rebake_npcf_hyperdense_blade_ultra": "DefaultMelee",
    "npc-rebake_npcf_miniaturized_railgun_ultra": "Railgun",
    "npc-rebake_npcf_nova_missiles_ultra": "Missiles",
    "npc-rebake_npcf_ravager_turret_ultra": "HMG",
    "npc-rebake_npcf_wraith_nexus_ultra": "Nexus",
    "nrfaw-npc-rebake_npcf_judgement_shotgun_avenger": "Shotgun",
    "nrfaw-npc-rebake_npcf_scouring_whip_lurker": "Nanobot Whip",
    "nrfaw-npc-rebake_npcf_slug_pistol_avenger": "Pistol",
    "nrfaw-npc-rebake_npcf_marksman_kit_ranger_long_rifle_strider": "AMR",
    "nrfaw-npc-rebake_npcf_skirmisher_kit_explosive_carbine_strider": "Bolt Thrower",
    "nrfaw-npc-rebake_npcf_survival_knife_strider": "DefaultMelee",

    //HEURISTICS
    "lwfx_heuristic_melee": "DefaultMelee",
    "lwfx_heuristic_cqb_energy": "PPC",
    "lwfx_heuristic_cqb_shotgun": "Shotgun",
    "lwfx_heuristic_cqb_other": "Pistol",
    "lwfx_heuristic_cannon_energy": "Tachyon Lance",
    "lwfx_heuristic_cannon_mg": "HMG",
    "lwfx_heuristic_cannon_other": "Mortar",
    "lwfx_heuristic_launcher": "Missile",
    "lwfx_heuristic_nexus": "Nexus",
    "lwfx_heuristic_rifle_energy": "Thermal Rifle",
    "lwfx_heuristic_rifle_mg": "HMG",
    "lwfx_heuristic_rifle_ar": "Assault Rifle",
    "lwfx_heuristic_rifle_other": "AMR",
};
